language: node_js
node_js:
  - 16
cache:
  directories:
  - node_modules
  - latex-playground/node_modules
script:
  - npm install && npm run build
  - npm run test
after_failure: cat /home/travis/.npm/_logs/*-debug.log
warnings_are_errors: false
env:
  CI=false